openapi: "3.0.3"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1
security:
  - BearerAuth: []

paths:
  /login:
    post:
      summary: Login
      description: Login to the system
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/AuthResponse"
  /register:
    post:
      summary: Register
      description: Register a new user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - phone
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
                phone:
                  type: string
      responses:
        "201":
          $ref: "#/components/responses/AuthResponse"
  /logout:
    post:
      summary: Logout
      description: Logout from the system (invalidate token in header)
      responses:
        "200":
          description: Successful logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logged out successfully"
  /refresh:
    post:
      summary: Refresh Token
      description: Refresh the access token using the refresh token
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
      responses:
        "200":
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - accessToken
                properties:
                  accessToken:
                    type: string
                    example: abcdef1234567890
  /accounts:
    get:
      summary: Get users information
      parameters:
        - name: search
          in: query
          description: Search by name
          required: false
          schema:
            type: string
            example: John
        - name: role
          in: query
          description: Filter by role (1 - Client, 2 - CMS)
          required: false
          schema:
            type: number
            enum:
              - 1
              - 2
            example: 1
        - $ref: "./common.yml#/components/parameters/page"
        - $ref: "./common.yml#/components/parameters/limit"
      responses:
        "200":
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination:
                    $ref: "./common.yml#/components/schemas/Pagination"
                  accounts:
                    type: array
                    description: List of user information
                    items:
                      $ref: "#/components/schemas/User"
  /accounts/{accountId}:
    get:
      summary: Get User Info
      description: Get user information by account ID
      parameters:
        - $ref: "#/components/parameters/AccountId"
      responses:
        "200":
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /accounts/many:
    get:
      summary: Get Multiple User Info
      description: Get multiple user information by account IDs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - accountIds
              properties:
                accountIds:
                  type: array
                  items:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
      responses:
        "200":
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
components:
  schemas:
    Role:
      type: number
      enum:
        - 1
        - 2
      description: Role of the user (1 - Client, 2 - CMS)
    UserAuth:
      type: object
      required:
        - accountId
        - role
        - name
        - phone
        - email
      properties:
        accountId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          example: John Doe
        role:
          $ref: "#/components/schemas/Role"
        phone:
          type: string
          example: +1234567890
        email:
          type: string
          example: johndoe@gmail.com
          format: email
        avatar:
          type: string
          example: https://example.com/avatar.jpg
    TokenAuth:
      type: object
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
          example: abcdef1234567890
        refreshToken:
          type: string
          example: ghijkl0987654321
    User:
      type: object
      allOf:
        - $ref: "#/components/schemas/UserAuth"
        - $ref: "./common.yml#/components/schemas/TimestampFields"
  parameters:
    AccountId:
      name: accountId
      in: path
      required: true
      description: Account ID of the user
      schema:
        type: string
        format: uuid
        example: 123e4567-e89b-12d3-a456-426614174000
  responses:
    AuthResponse:
      description: Successful login response
      content:
        application/json:
          schema:
            type: object
            required:
              - user
              - token
            properties:
              user:
                $ref: "#/components/schemas/UserAuth"
              token:
                $ref: "#/components/schemas/TokenAuth"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
