openapi: "3.0.3"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1
security:
  - BearerAuth: []

paths:
  /login:
    post:
      summary: Login
      description: Login to the system
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/AuthResponse"
  /google:
    post:
      summary: Google Login
      description: Login to the system using Google OAuth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: Google OAuth token
      responses:
        "200":
          $ref: "#/components/responses/AuthResponse"
  /register:
    post:
      summary: Register
      description: Register a new user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - phone
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
                phone:
                  type: string
                avatar:
                  type: string
                  description: User avatar image (File upload)
      responses:
        "201":
          $ref: "#/components/responses/AuthResponse"
  /refresh:
    post:
      summary: Refresh Token
      description: Refresh the access token using the refresh token
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
      responses:
        "200":
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    $ref: "#/components/schemas/TokenAuth"
  /accounts/{accountId}:
    get:
      summary: Get User Info
      description: Get user information by account ID
      parameters:
        - $ref: "#/components/parameters/AccountId"
      responses:
        "200":
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /accounts/many:
    post:
      summary: Get Multiple User Info
      description: Get multiple user information by account IDs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - accountIds
              properties:
                accountIds:
                  type: array
                  items:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
      responses:
        "200":
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

  /stores/{storeId}/login:
    post:
      summary: Store Login
      description: Login to the system with store ID
      security: []
      parameters:
        - $ref: "#/components/parameters/StoreId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/CMSAuthResponse"
  /stores/{storeId}/register/{inviteCode}:
    post:
      summary: Store Register
      description: Register a new user in the store after the invitation
      security: []
      parameters:
        - $ref: "#/components/parameters/StoreId"
        - name: inviteCode
          in: path
          required: true
          description: Invitation code for the store
          schema:
            type: string
            example: "INVITE1234"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - phone
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                name:
                  type: string
                phone:
                  type: string
                avatar:
                  type: string
                  description: User avatar image (File upload)
                timezone:
                  type: string
                  description: Timezone of the user
      responses:
        "201":
          $ref: "#/components/responses/CMSAuthResponse"
  
  /reset-password:
    post:
      summary: Reset Password
      description: Reset user password using special reset code
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - code
                - newPassword
              properties:
                code:
                  type: string
                  description: Special reset code sent to the user's email
                newPassword:
                  type: string
                  description: New password for the user
      responses:
        "201":
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Password reset successfully"

  # Version 2 endpoints: Uses HTTP only cookies for token management

  /v2/register:
    post:
      summary: Register V2
      description: Register a new user (Version 2)
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - phone
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
                phone:
                  type: string
                avatar:
                  type: string
                  description: User avatar image (File upload)
      responses:
        "201":
          $ref: "#/components/responses/AuthResponse2"
  /v2/login:
    post:
      summary: Login V2
      description: Login to the system (Version 2)
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/AuthResponse2"
  /v2/google:
    post:
      summary: Google Login V2
      description: Login to the system using Google OAuth (Version 2)
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: Google OAuth token
      responses:
        "200":
          $ref: "#/components/responses/AuthResponse2"
  /v2/refresh:
    post:
      summary: Refresh Token V2
      description: Refresh the access token using the refresh token (Version 2)
      security: []
      responses:
        "200":
          $ref: "#/components/responses/AuthResponse2"
  /v2/accounts/{accountId}:
    get:
      summary: Get User Info V2
      description: Get user information by account ID (Version 2)
      parameters:
        - $ref: "#/components/parameters/AccountId"
      responses:
        "200":
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /v2/accounts/many:
    post:
      summary: Get Multiple User Info V2
      description: Get multiple user information by account IDs (Version 2)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - accountIds
              properties:
                accountIds:
                  type: array
                  items:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
      responses:
        "200":
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

  /v2/stores/{storeId}/login:
    post:
      summary: Store Login V2
      description: Login to the system with store ID (Version 2)
      security: []
      parameters:
        - $ref: "#/components/parameters/StoreId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/CMSAuthResponse"
  /v2/stores/{storeId}/register/{inviteCode}:
    post:
      summary: Store Registration V2
      description: Register a new user in the store after the invitation (Version 2)
      security: []
      parameters:
        - $ref: "#/components/parameters/StoreId"
        - name: inviteCode
          in: path
          required: true
          description: Invitation code for the store
          schema:
            type: string
            example: "INVITE1234"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - phone
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                name:
                  type: string
                phone:
                  type: string
                avatar:
                  type: string
                  description: User avatar image (File upload)
                timezone:
                  type: string
                  description: Timezone of the user
      responses:
        "201":
          $ref: "#/components/responses/CMSAuthResponse2"
  
  /v2/reset-password:
    post:
      summary: Reset Password V2
      description: Reset user password using special reset code (Version 2)
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - code
                - newPassword
              properties:
                code:
                  type: string
                  description: Special reset code sent to the user's email
                newPassword:
                  type: string
                  description: New password for the user
      responses:
        "201":
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Password reset successfully"

components:
  schemas:
    Role:
      type: number
      enum:
        - 1
        - 2
      description: Role of the user (1 - Client, 2 - CMS)
    CmsRole:
      type: number
      enum:
        - 1
        - 2
        - 3
      description: CMS role of the user (1 - Admin, 2 - Manager, 3 - Employee)

    User:
      type: object
      required:
        - accountId
        - role
        - name
        - phone
        - email
      properties:
        accountId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          example: John Doe
        role:
          $ref: "#/components/schemas/Role"
        phone:
          type: string
          example: +1234567890
        email:
          type: string
          example: johndoe@gmail.com
          format: email
        address:
          type: string
          example: 123 Main St, City, Country
        avatar:
          type: string
          example: https://example.com/avatar.jpg
        isGoogle:
          type: boolean
          example: false
          description: Indicates if the user registered via Google OAuth
    TokenAuth:
      type: object
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
          example: abcdef1234567890
        refreshToken:
          type: string
          example: ghijkl0987654321
    CMSUser:
      allOf:
        - $ref: "#/components/schemas/User"
        - type: object
          required:
            - cmsRole
            - storeId
          properties:
            cmsRole:
              $ref: "#/components/schemas/CmsRole"
            storeId:
              type: string
              format: uuid
              example: 123e4567-e89b-12d3-a456-426614174000

  parameters:
    AccountId:
      name: accountId
      in: path
      required: true
      description: Account ID of the user
      schema:
        type: string
        format: uuid
        example: 123e4567-e89b-12d3-a456-426614174000
    StoreId:
      name: storeId
      in: path
      required: true
      description: Store ID of the user
      schema:
        type: string
        format: uuid
        example: 123e4567-e89b-12d3-a456-426614174000

  responses:
    AuthResponse:
      description: Successful login response
      content:
        application/json:
          schema:
            type: object
            required:
              - user
              - token
            properties:
              user:
                $ref: "#/components/schemas/User"
              token:
                $ref: "#/components/schemas/TokenAuth"
    CMSAuthResponse:
      description: Successful CMS login response
      content:
        application/json:
          schema:
            type: object
            required:
              - user
              - token
            properties:
              user:
                $ref: "#/components/schemas/CMSUser"
              token:
                $ref: "#/components/schemas/TokenAuth"

    AuthResponse2:
      description: Successful login response (Version 2)
      content:
        application/json:
          schema:
            type: object
            required:
              - user
              - token
            properties:
              user:
                $ref: "#/components/schemas/User"
    CMSAuthResponse2:
      description: Successful CMS login response (Version 2)
      content:
        application/json:
          schema:
            type: object
            required:
              - user
              - token
            properties:
              user:
                $ref: "#/components/schemas/CMSUser"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
